# Generated by Django 3.1.7 on 2021-03-28 23:07

from django.db import migrations

sql_command = """
DROP TABLE IF EXISTS django_session;
"""


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(sql_command)
    ]
