# Generated by Django 3.1.7 on 2021-03-29 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='gender',
            field=models.CharField(default='male', max_length=6),
        ),
    ]
