# Generated by Django 3.1.7 on 2021-03-29 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0004_auto_20210329_0047'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='trainer',
            table='trainer',
        ),
    ]
